In [2]:
import torch


x = torch.arange(4.0)

x

tensor([0., 1., 2., 3.])

在我们计算```y```关于```X```的梯度之前，我们需要一个地方来存储梯度。

In [3]:
x.requires_grad_(True)
x.grad

现在让我们计算```y```

In [4]:
y = 2 * torch.dot(x, x)

y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来自动计算```y```关于```X```每个分量的梯度

In [5]:
y.backward()

x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
x.grad == 4 * x

tensor([True, True, True, True])

现在让我们计算```X```的另一个函数

In [7]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()

y = x.sum()
y.backward()

x.grad

tensor([1., 1., 1., 1.])

将某些计算移动到记录的计算图之外

In [ ]:
x.grad.zero_()
y = x * x
u = y.detach() # u 是一个没有梯度的张量
z = u * x # z 现在是一个关于 x 的函数

z.sum().backward()

x.grad == u

tensor([True, True, True, True])

In [12]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])